name: Testing with conditions
on:
  push:
  workflow_dispatch:
    
env:
  environmentname: Production
  url: ${{secrets.QA_URL}}
  
jobs:
  urlTestingConfirm:
    runs-on: ubuntu-latest
    steps:
      - name: URLname
        run: |
          echo "Runnning test on ${{env.url}}for $environmentname"
      - name: Print if QA URL
        if: ${{env.environmentname=='QA'}}
        run: echo "Hey your test will be run on the QA Environment...."
      - name: Print if Prod URL
        if: ${{env.environmentname=='Production'}}
        run: echo "Hey your test will run on the Production Environment...."
      - name: Print if Dev URL
        if: ${{env.environmentname=='Dev'}}
        run: echo "Hey your test will be run on the Dev Environment...."
      - name: Github actor
        run: |
          echo "Github_Actor_variable_name : $GITHUB_ACTOR"
          echo "Github_Job_variable_name : $GITHUB_JOB"
          
     # - name: checkout project repository
      #  uses: actions/checkout@v2
        
      #- name: Setup Maven
       # uses: actions/setup-maven@v3.6
       # with: 
        #  maven-version: 3.8.6
      #- name: Setup JDK Version 11
       # uses: actions/setup-java@v3
        #with:
         # java-version: 11
          
        
        
        
        
